name: Download FIRMS Global data

on:
  schedule:
    - cron: "0 1,13 * * *"   # 
  workflow_dispatch: {}

jobs:
  download:
    runs-on: ubuntu-latest
    env:
      EARTHDATA_TOKEN: ${{ secrets.EARTHDATA_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'stable'

      - name: Install required R packages
        run: |
          Rscript -e 'install.packages(c("httr2","rvest","xml2"), repos="https://cran.rstudio.com")'

      - name: Run FIRMS download script
        run: Rscript scripts/aux_download_firms_data_via_https.r

      - name: Commit and push new data
        run: |
          if [ -n "$(git status --porcelain source-data/firms-imports/2025 || true)" ]; then
            git config user.name "github-actions"
            git config user.email "actions@users.noreply.github.com"
            git add source-data/firms-imports/2025
            git commit -m "Update FIRMS data $(date -u +'%Y-%m-%d %H:%M UTC')"
            git push
          else
            echo "No new files."
          fi
